### ISSUE TITLE
Getting answers to the wrong conversations

### ISSUE THREAD

**Issue by Explosion-Scratch** [proxoar/talk#85]
<img width="1712" alt="image" src="https://github.com/proxoar/talk/assets/61319150/343f376c-eed4-426f-bb9c-3c0d5fa4bf7b">
<img width="889" alt="image" src="https://github.com/proxoar/talk/assets/61319150/64084ea4-6e7c-4406-8921-3a5c3406103f">
<img width="895" alt="image" src="https://github.com/proxoar/talk/assets/61319150/eb214487-62a3-44f2-94a7-75fbfadae5f5">
<img width="892" alt="image" src="https://github.com/proxoar/talk/assets/61319150/b3189485-ae6d-419f-8d5e-cd43e81c35b0">
<img width="895" alt="image" src="https://github.com/proxoar/talk/assets/61319150/0582d897-7125-4dc2-ae60-91af1fe6a2da">
<img width="893" alt="image" src="https://github.com/proxoar/talk/assets/61319150/a2f54a4e-9873-4469-ad81-eeaf967f1698">
<img width="884" alt="image" src="https://github.com/proxoar/talk/assets/61319150/70375089-cf4e-40b4-9bd0-b979fc9f601a">

Settings are at default

**Comment by proxfly** [comment]
Could you provide additional information to assist in diagnosing the issue more effectively?
* Were you using talk.proxoar.com or your own deployed instance?
* Could you please share the content of your talk.yaml file (ensuring the API key is sanitized)?

If you were using talk.proxoar.com, it's important to note that it is a demo and does not utilize the real ChatGPT, therefore, the response is expected to be incorrect.

**Comment by Explosion-Scratch** [comment]
> If you were using talk.proxoar.com, it's important to note that it is a demo and does not utilize the real ChatGPT, therefore, the response is expected to be incorrect.

Oh yeah, I was using the demo. Maybe mention that in the responses lol

**Comment by proxfly** [comment]
> > If you were using talk.proxoar.com, it's important to note that it is a demo and does not utilize the real ChatGPT, therefore, the response is expected to be incorrect.
> 
> Oh yeah, I was using the demo. Maybe mention that in the responses lol

It's a good idea to mention that in responses👍. An update should be rolled out later today.
